### PR TITLE
support to call from package name

### PR DESCRIPTION
**Pull request by funcphp**
Call main file using the package name

Ex:
```js
plugins: [
    new ConcatPlugin({
    ...
        filesToConcat: [
            'jquery',
            'bootstrap',
            'smooth-scrollbar',
            'isotope-layout',
        ]
    })
]
```

### CODE REVIEW

**Comment by hxlniada** [comment]
sound good, but is it better to use require.resolve to get the filepath?

**Comment by funcphp** [comment]
@hxlniada I didn't know that. Is it possible to get the package main file with the require.resolve?

**Comment by hxlniada** [comment]
@funcphp https://nodejs.org/api/modules.html#modules_require_resolve
It return the absolute path of the main file.
If the main file doesn't exist, it throw an error.
for example:
```
require.resolve('uglify-js')
```
the result is
```
/Users/Username/Documents/learn/webpack-concat-plugin/node_modules/uglify-js/tools/node.js
```
in my computer.
but
```
require.resolve('uglify-js')
```
will throw an error
```
module.js:487
    throw err;
    ^

Error: Cannot find module '11'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/Users/huangxueliang/Documents/learn/webpack-concat-plugin/app.js:1:83)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
```

**Comment by funcphp** [comment]
@hxlniada Nice... what do you think about updating repo for this purpose?

**Comment by hxlniada** [comment]
I think it's really useful 🙂

**Comment by funcphp** [comment]
@hxlniada let's do it :)

**Comment by hxlniada** [comment]
update to 2.0.0 and try again

**Pull request closed without merging**
